// GENERATED by scripts/gen-registry.mjs — do not edit.
// Run `npm run gen:registry` after adding or removing a resource folder.
//
// Importing this module registers every resource. A deployment that only needs some of them
// should import those directly instead: `import '@struct8/hub/r/aws_sqs_queue'`.

import './aws_api_gateway_rest_api/index.js';
import './aws_appsync_graphql_api/index.js';
import './aws_cloudfront_distribution/index.js';
import './aws_cloudwatch_event_bus/index.js';
import './aws_cloudwatch_event_rule/index.js';
import './aws_cloudwatch_log_group/index.js';
import './aws_cognito_user_pool/index.js';
import './aws_db_instance/index.js';
import './aws_db_proxy/index.js';
import './aws_dynamodb_table/index.js';
import './aws_kinesis_firehose_delivery_stream/index.js';
import './aws_kinesis_stream/index.js';
import './aws_kinesis_video_stream/index.js';
import './aws_lambda_function/index.js';
import './aws_lambda_function_url/index.js';
import './aws_lb/index.js';
import './aws_rds_cluster/index.js';
import './aws_s3_bucket/index.js';
import './aws_secretsmanager_secret/index.js';
import './aws_sns_topic/index.js';
import './aws_sqs_queue/index.js';
import './aws_ssm_parameter/index.js';

/** Every resource type this build knows about, in registration order. */
export const BUNDLED: readonly string[] = [ "aws_api_gateway_rest_api", "aws_appsync_graphql_api", "aws_cloudfront_distribution", "aws_cloudwatch_event_bus", "aws_cloudwatch_event_rule", "aws_cloudwatch_log_group", "aws_cognito_user_pool", "aws_db_instance", "aws_db_proxy", "aws_dynamodb_table", "aws_kinesis_firehose_delivery_stream", "aws_kinesis_stream", "aws_kinesis_video_stream", "aws_lambda_function", "aws_lambda_function_url", "aws_lb", "aws_rds_cluster", "aws_s3_bucket", "aws_secretsmanager_secret", "aws_sns_topic", "aws_sqs_queue", "aws_ssm_parameter" ];
