// GENERATED by scripts/gen-registry.mjs — do not edit.
// Run `npm run gen:registry` after adding or removing a resource folder.
//
// Importing this module registers every resource. A deployment that only needs some of them
// should import those directly instead: `import '@struct8/hub/r/aws_sqs_queue'`.

import './aws_s3_bucket/index.js';
import './aws_sns_topic/index.js';
import './aws_sqs_queue/index.js';

/** Every resource type this build knows about, in registration order. */
export const BUNDLED: readonly string[] = [ "aws_s3_bucket", "aws_sns_topic", "aws_sqs_queue" ];
